#requires -Version 7.0
#requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '5.0' }

Describe 'Generate-ReadmeFacts' {

    BeforeAll {
        $script:_origLastExit = $global:LASTEXITCODE
        $script:RepoRoot     = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
        $script:ScriptPath   = Join-Path $script:RepoRoot 'scripts\Generate-ReadmeFacts.ps1'
        $script:ManifestPath = Join-Path $script:RepoRoot 'tools\tool-manifest.json'
        $script:ReadmePath   = Join-Path $script:RepoRoot 'README.md'
        $script:Manifest     = Get-Content -LiteralPath $script:ManifestPath -Raw | ConvertFrom-Json
        $script:EnabledCount = @($script:Manifest.tools | Where-Object { $_.enabled }).Count
    }

    AfterAll {
        $global:LASTEXITCODE = $script:_origLastExit
    }

    It 'generator script exists' {
        Test-Path -LiteralPath $script:ScriptPath | Should -BeTrue
    }

    It 'manifest exposes at least one enabled tool' {
        $script:EnabledCount | Should -BeGreaterThan 0
    }

    Context 'README contains all required marker pairs' {
        BeforeAll {
            $script:ReadmeRaw = Get-Content -LiteralPath $script:ReadmePath -Raw
        }

        It 'has the tool-count-tagline BEGIN/END markers' {
            $script:ReadmeRaw | Should -Match '<!-- BEGIN: tool-count-tagline'
            $script:ReadmeRaw | Should -Match '<!-- END: tool-count-tagline -->'
        }

        It 'has the tool-count-feature-list BEGIN/END markers' {
            $script:ReadmeRaw | Should -Match '<!-- BEGIN: tool-count-feature-list'
            $script:ReadmeRaw | Should -Match '<!-- END: tool-count-feature-list -->'
        }

        It 'has the tool-catalog-summary BEGIN/END markers' {
            $script:ReadmeRaw | Should -Match '<!-- BEGIN: tool-catalog-summary'
            $script:ReadmeRaw | Should -Match '<!-- END: tool-catalog-summary -->'
        }
    }

    Context 'CheckOnly mode against the committed tree' {
        It 'reports the committed README is in sync with the manifest' {
            $output = & $script:ScriptPath -CheckOnly 2>&1
            $LASTEXITCODE | Should -Be 0 -Because "Generator -CheckOnly should pass on a clean tree. Output:`n$output"
        }
    }

    Context 'generation against a temp README is idempotent' {
        BeforeAll {
            $script:TempReadme = Join-Path $TestDrive ("readme-{0}.md" -f ([Guid]::NewGuid()))
            $template = @"
# fixture

<!-- BEGIN: tool-count-tagline (generated by scripts/Generate-ReadmeFacts.ps1; do not edit by hand) -->
**Stale tagline placeholder.**
<!-- END: tool-count-tagline -->

## intro

<!-- BEGIN: tool-count-feature-list (generated by scripts/Generate-ReadmeFacts.ps1; do not edit by hand) -->
- stale list placeholder
<!-- END: tool-count-feature-list -->

<!-- BEGIN: tool-catalog-summary (generated by scripts/Generate-ReadmeFacts.ps1; do not edit by hand) -->
<details><summary><b>stale summary placeholder</b></summary>
<!-- END: tool-catalog-summary -->
"@
            [System.IO.File]::WriteAllText($script:TempReadme, $template, [System.Text.UTF8Encoding]::new($false))
            & $script:ScriptPath -ReadmePath $script:TempReadme | Out-Null
            $script:FirstWrite = Get-Content -LiteralPath $script:TempReadme -Raw
            & $script:ScriptPath -ReadmePath $script:TempReadme | Out-Null
            $script:SecondWrite = Get-Content -LiteralPath $script:TempReadme -Raw
        }

        AfterAll {
            Remove-Item -LiteralPath $script:TempReadme -Force -ErrorAction SilentlyContinue
        }

        It 'replaces the tagline with the live manifest enabled count' {
            $expected = "**One PowerShell command, $($script:EnabledCount) read-only assessment tools (+ 1 opt-in)"
            $script:FirstWrite | Should -BeLike "*$expected*"
        }

        It 'replaces the feature-list bullet with the live manifest enabled count' {
            $expected = "- **$($script:EnabledCount) tools** (+ 1 opt-in)"
            $script:FirstWrite | Should -BeLike "*$expected*"
        }

        It 'replaces the catalog summary with the live manifest enabled count' {
            $expected = "<details><summary><b>Tool catalog ($($script:EnabledCount) enabled + 1 opt-in)</b></summary>"
            $script:FirstWrite | Should -BeLike "*$expected*"
        }

        It 'produces no diff on a second run (idempotent invariant)' {
            $script:FirstWrite | Should -Be $script:SecondWrite
        }

        It 'never emits an em dash' {
            $script:FirstWrite | Should -Not -Match ([char]0x2014)
        }
    }

    Context 'CheckOnly mode fails when README is stale' {
        It 'exits 1 when an auto-managed section is out of sync' {
            $tempReadme = Join-Path $TestDrive ("stale-{0}.md" -f ([Guid]::NewGuid()))
            $template = @"
# fixture

<!-- BEGIN: tool-count-tagline (generated by scripts/Generate-ReadmeFacts.ps1; do not edit by hand) -->
**STALE.**
<!-- END: tool-count-tagline -->

<!-- BEGIN: tool-count-feature-list (generated by scripts/Generate-ReadmeFacts.ps1; do not edit by hand) -->
- STALE
<!-- END: tool-count-feature-list -->

<!-- BEGIN: tool-catalog-summary (generated by scripts/Generate-ReadmeFacts.ps1; do not edit by hand) -->
STALE
<!-- END: tool-catalog-summary -->
"@
            try {
                [System.IO.File]::WriteAllText($tempReadme, $template, [System.Text.UTF8Encoding]::new($false))
                & $script:ScriptPath -ReadmePath $tempReadme -CheckOnly 2>&1 | Out-Null
                $LASTEXITCODE | Should -Be 1
            } finally {
                Remove-Item -LiteralPath $tempReadme -Force -ErrorAction SilentlyContinue
                $global:LASTEXITCODE = 0
            }
        }
    }

    Context 'generator throws clearly when markers are missing' {
        It 'reports which marker pair is missing' {
            $tempReadme = Join-Path $TestDrive ("nomark-{0}.md" -f ([Guid]::NewGuid()))
            try {
                Set-Content -LiteralPath $tempReadme -Value "# README without markers" -NoNewline
                $err = $null
                try {
                    & $script:ScriptPath -ReadmePath $tempReadme 2>&1 | Out-Null
                } catch {
                    $err = $_
                }
                $err | Should -Not -BeNullOrEmpty
                # The throw message includes the marker id name; on a fresh README the
                # first missing marker is the tagline.
                "$err" | Should -Match 'tool-count-tagline'
            } finally {
                Remove-Item -LiteralPath $tempReadme -Force -ErrorAction SilentlyContinue
                $global:LASTEXITCODE = 0
            }
        }
    }
}
