#requires -Version 7.0
#requires -Modules @{ ModuleName = 'Pester'; ModuleVersion = '5.0' }

Describe 'Generate-PermissionsIndex' {

    BeforeAll {
        $script:RepoRoot      = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
        $script:ScriptPath    = Join-Path $script:RepoRoot 'scripts\Generate-PermissionsIndex.ps1'
        $script:ManifestPath  = Join-Path $script:RepoRoot 'tools\tool-manifest.json'
        $script:Permissions   = Join-Path $script:RepoRoot 'PERMISSIONS.md'
        $script:PagesDir      = Join-Path $script:RepoRoot 'docs\consumer\permissions'
        $script:Manifest      = Get-Content -LiteralPath $script:ManifestPath -Raw | ConvertFrom-Json
        $script:EnabledTools  = @($script:Manifest.tools | Where-Object { $_.enabled })
    }

    It 'generator script exists' {
        Test-Path -LiteralPath $script:ScriptPath | Should -BeTrue
    }

    It 'PERMISSIONS.md exists at the repo root' {
        Test-Path -LiteralPath $script:Permissions | Should -BeTrue
    }

    It 'permissions pages directory exists' {
        Test-Path -LiteralPath $script:PagesDir | Should -BeTrue
    }

    It 'PERMISSIONS.md contains the BEGIN INDEX / END INDEX markers' {
        $content = Get-Content -LiteralPath $script:Permissions -Raw
        $content | Should -Match '<!-- BEGIN INDEX'
        $content | Should -Match '<!-- END INDEX -->'
    }

    It 'every enabled manifest tool has a docs/consumer/permissions/<name>.md page' {
        $missing = @()
        foreach ($t in $script:EnabledTools) {
            $path = Join-Path $script:PagesDir "$($t.name).md"
            if (-not (Test-Path -LiteralPath $path)) { $missing += $t.name }
        }
        $missing | Should -BeNullOrEmpty -Because "missing pages: $($missing -join ', ')"
    }

    It 'every per-tool page has the standard H1 heading' {
        foreach ($t in $script:EnabledTools) {
            $path = Join-Path $script:PagesDir "$($t.name).md"
            $first = (Get-Content -LiteralPath $path -TotalCount 1)
            $first | Should -Match '^# .* - Required Permissions$' -Because "page for $($t.name) should start with an H1 ending in '- Required Permissions'"
        }
    }

    It 'cross-cutting framework pages all exist' {
        foreach ($name in @('_summary.md','_continuous-control.md','_multi-tenant.md','_management-group.md','_troubleshooting.md','README.md')) {
            $path = Join-Path $script:PagesDir $name
            Test-Path -LiteralPath $path | Should -BeTrue -Because "expected $name in $script:PagesDir"
        }
    }

    Context 'CheckOnly mode against the committed tree' {
        It 'reports the committed PERMISSIONS.md is in sync with the manifest' {
            $output = & $script:ScriptPath -CheckOnly 2>&1
            $LASTEXITCODE | Should -Be 0 -Because "Generator -CheckOnly should pass on a clean tree. Output:`n$output"
        }
    }

    Context 'generation against a temp PERMISSIONS.md is idempotent' {
        BeforeAll {
            $script:TempPerm = Join-Path ([System.IO.Path]::GetTempPath()) ("permissions-{0}.md" -f ([Guid]::NewGuid()))
            $template = "# Test`n`n<!-- BEGIN INDEX (generated by scripts/Generate-PermissionsIndex.ps1; do not edit by hand) -->`n<!-- END INDEX -->`n"
            [System.IO.File]::WriteAllText($script:TempPerm, $template, [System.Text.UTF8Encoding]::new($false))
            & $script:ScriptPath -PermissionsPath $script:TempPerm | Out-Null
            $script:FirstWrite = Get-Content -LiteralPath $script:TempPerm -Raw
            & $script:ScriptPath -PermissionsPath $script:TempPerm | Out-Null
            $script:SecondWrite = Get-Content -LiteralPath $script:TempPerm -Raw
        }

        AfterAll {
            Remove-Item -LiteralPath $script:TempPerm -Force -ErrorAction SilentlyContinue
        }

        It 'produces a non-empty INDEX section' {
            $script:FirstWrite | Should -Match ([regex]::Escape('docs/consumer/permissions/azqr.md'))
        }

        It 'produces an entry for every enabled tool' {
            foreach ($t in $script:EnabledTools) {
                $script:FirstWrite | Should -Match ([regex]::Escape("docs/consumer/permissions/$($t.name).md"))
            }
        }

        It 'produces no diff on a second run' {
            $script:FirstWrite | Should -Be $script:SecondWrite
        }
    }
}
